# Generated by Django 5.1.4 on 2026-06-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=120)),
                ('afro_subregion', models.CharField(db_index=True, max_length=40)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('priority_country', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('disease', models.CharField(db_index=True, max_length=60)),
                ('cases_reported', models.BigIntegerField(blank=True, null=True)),
                ('deaths_reported', models.BigIntegerField(blank=True, null=True)),
                ('attack_rate_per_100k', models.FloatField(blank=True, null=True)),
                ('case_fatality_ratio_pct', models.FloatField(blank=True, null=True)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('quality_notes', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'indexes': [models.Index(fields=['disease', 'year'], name='surveillanc_disease_90f2a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'year', 'disease'), name='uq_disease_country_year_disease')],
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('total_funding_usd', models.BigIntegerField(blank=True, null=True)),
                ('domestic_funding_usd', models.BigIntegerField(blank=True, null=True)),
                ('external_funding_usd', models.BigIntegerField(blank=True, null=True)),
                ('funding_per_capita_usd', models.FloatField(blank=True, null=True)),
                ('domestic_funding_share_pct', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uq_funding_country_year')],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('total_public_labs', models.IntegerField(blank=True, null=True)),
                ('labs_iso15189_accredited', models.IntegerField(blank=True, null=True)),
                ('iso15189_accreditation_pct', models.FloatField(blank=True, null=True)),
                ('avg_turnaround_time_days', models.FloatField(blank=True, null=True)),
                ('diagnostic_tests_per_100k', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uq_lab_country_year')],
            },
        ),
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('outbreak_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('disease', models.CharField(db_index=True, max_length=60)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('time_to_detection_days', models.IntegerField(blank=True, null=True)),
                ('cases', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'year'], name='surveillanc_country_3cf155_idx')],
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('total_population', models.BigIntegerField(blank=True, null=True)),
                ('under5_population', models.BigIntegerField(blank=True, null=True)),
                ('urban_population_pct', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uq_population_country_year')],
            },
        ),
        migrations.CreateModel(
            name='ReportingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('timeliness_pct', models.FloatField(blank=True, null=True)),
                ('completeness_pct', models.FloatField(blank=True, null=True)),
                ('idsr_weekly_compliance_pct', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uq_reporting_country_year')],
            },
        ),
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('epidemiologists_total', models.IntegerField(blank=True, null=True)),
                ('epidemiologists_per_100k', models.FloatField(blank=True, null=True)),
                ('feltp_trained_total', models.IntegerField(blank=True, null=True)),
                ('feltp_trained_pct', models.FloatField(blank=True, null=True)),
                ('lab_technicians_total', models.IntegerField(blank=True, null=True)),
                ('lab_technicians_per_100k', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uq_workforce_country_year')],
            },
        ),
    ]
