# Generated by Django 5.1.4 on 2026-06-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasesurveillance',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='diseasesurveillance',
            name='under_ascertainment',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
