# Profiles every raw CSV and writes docs/data_quality_report.md. Read-only: it just
# reports issues (missing values, impossible/contradictory rows, range checks).
# The actual cleaning happens in the ETL (load_data.py) so it stays auditable.

from __future__ import annotations

import io
from pathlib import Path

import pandas as pd

RAW = Path(__file__).resolve().parent.parent / "data" / "raw"
REPORT = Path(__file__).resolve().parent.parent / "docs" / "data_quality_report.md"

EXPECTED_COUNTRIES = 20
YEARS = list(range(2021, 2026))  # 2021-2025 inclusive

FILES = [
    "countries.csv",
    "population.csv",
    "disease_surveillance.csv",
    "outbreaks.csv",
    "laboratory_capacity.csv",
    "reporting_metrics.csv",
    "workforce.csv",
    "funding.csv",
]


def section(title: str) -> str:
    return f"\n\n## {title}\n"


def df_overview(df: pd.DataFrame) -> str:
    buf = io.StringIO()
    buf.write(f"- Rows: **{len(df)}**, Columns: **{df.shape[1]}**\n")
    buf.write(f"- Columns: `{', '.join(df.columns)}`\n")
    # null counts
    nulls = df.isna().sum()
    nulls = nulls[nulls > 0]
    if len(nulls):
        buf.write("- **Missing values:**\n")
        for col, n in nulls.items():
            buf.write(f"    - `{col}`: {n} ({n / len(df):.1%})\n")
    else:
        buf.write("- Missing values: none\n")
    # duplicates
    dups = df.duplicated().sum()
    buf.write(f"- Fully duplicated rows: {dups}\n")
    return buf.getvalue()


def numeric_ranges(df: pd.DataFrame, cols: list[str]) -> str:
    buf = io.StringIO()
    buf.write("- Numeric ranges:\n")
    for c in cols:
        if c in df.columns and pd.api.types.is_numeric_dtype(df[c]):
            s = df[c]
            buf.write(
                f"    - `{c}`: min={s.min():.3g}, max={s.max():.3g}, "
                f"mean={s.mean():.3g}, neg={int((s < 0).sum())}\n"
            )
    return buf.getvalue()


def main() -> None:
    out = io.StringIO()
    out.write("# Data Quality & Profiling Report\n")
    out.write(
        "_Auto-generated by `etl/profile_data.py`. The dataset is synthetic but "
        "representative of a regional surveillance context. Issues found here are "
        "handled explicitly in `etl/load.py`._\n"
    )

    frames: dict[str, pd.DataFrame] = {}
    for f in FILES:
        path = RAW / f
        df = pd.read_csv(path)
        frames[f] = df
        out.write(section(f"`{f}`"))
        out.write(df_overview(df))

    # ---- Per-file deeper checks -------------------------------------------
    countries = frames["countries.csv"]
    out.write(section("Cross-cutting checks"))

    # 1. country count
    iso_ref = set(countries["iso3"])
    out.write(f"- Reference countries: **{len(iso_ref)}** (expected {EXPECTED_COUNTRIES})\n")
    out.write(f"- priority_country values: {sorted(countries['priority_country'].unique())}\n")

    # 2. referential integrity: every fact iso3 must exist in countries
    out.write("\n### Referential integrity (iso3 in countries.csv?)\n")
    for f, df in frames.items():
        if f == "countries.csv" or "iso3" not in df.columns:
            continue
        orphan = set(df["iso3"]) - iso_ref
        out.write(f"- `{f}`: {'OK' if not orphan else f'ORPHANS {orphan}'}\n")

    # 3. panel completeness: 20 countries x 5 years for annual tables
    out.write("\n### Panel completeness (expected 20 countries x 5 years = 100 rows)\n")
    for f in ["population.csv", "laboratory_capacity.csv", "reporting_metrics.csv",
              "workforce.csv", "funding.csv"]:
        df = frames[f]
        n = len(df.drop_duplicates(["iso3", "year"]))
        yrs = sorted(df["year"].unique())
        missing = []
        for iso in iso_ref:
            present = set(df[df["iso3"] == iso]["year"])
            miss = set(YEARS) - present
            if miss:
                missing.append(f"{iso}:{sorted(miss)}")
        out.write(f"- `{f}`: {n} country-year rows, years={yrs}"
                  f"{'' if not missing else f', MISSING -> {missing}'}\n")

    # 4. duplicate keys on annual tables
    out.write("\n### Duplicate (iso3, year) keys\n")
    for f in ["population.csv", "laboratory_capacity.csv", "reporting_metrics.csv",
              "workforce.csv", "funding.csv"]:
        df = frames[f]
        d = df.duplicated(["iso3", "year"]).sum()
        out.write(f"- `{f}`: {d}\n")

    # 5. numeric sanity
    out.write(section("Numeric range / plausibility checks"))
    out.write("\n### population.csv\n")
    pop = frames["population.csv"]
    out.write(numeric_ranges(pop, ["total_population", "under5_population", "urban_population_pct"]))
    bad_pct = pop[(pop["urban_population_pct"] < 0) | (pop["urban_population_pct"] > 100)]
    out.write(f"- urban_population_pct outside 0-100: {len(bad_pct)}\n")
    bad_u5 = pop[pop["under5_population"] > pop["total_population"]]
    out.write(f"- under5 > total population: {len(bad_u5)}\n")
    # under-5 share volatility (NGA 2021 37.8M -> 2022 28.9M looks suspicious)
    pop_sorted = pop.sort_values(["iso3", "year"]).copy()
    pop_sorted["u5_share"] = pop_sorted["under5_population"] / pop_sorted["total_population"]
    out.write(f"- under5 share range: {pop_sorted['u5_share'].min():.1%} - {pop_sorted['u5_share'].max():.1%} "
              f"(implausibly wide swings suggest noisy under5 figures)\n")

    out.write("\n### reporting_metrics.csv (percentages should be 0-100)\n")
    rep = frames["reporting_metrics.csv"]
    out.write(numeric_ranges(rep, ["timeliness_pct", "completeness_pct", "idsr_weekly_compliance_pct"]))
    for c in ["timeliness_pct", "completeness_pct", "idsr_weekly_compliance_pct"]:
        bad = rep[(rep[c] < 0) | (rep[c] > 100)]
        out.write(f"- `{c}` outside 0-100: {len(bad)}\n")

    out.write("\n### funding.csv\n")
    fund = frames["funding.csv"]
    out.write(numeric_ranges(fund, ["total_funding_usd", "domestic_funding_usd",
                                    "external_funding_usd", "funding_per_capita_usd",
                                    "domestic_funding_share_pct"]))
    # does domestic + external = total (where both present)?
    fcheck = fund.dropna(subset=["domestic_funding_usd", "external_funding_usd"]).copy()
    fcheck["sum_components"] = fcheck["domestic_funding_usd"] + fcheck["external_funding_usd"]
    fcheck["diff_pct"] = (fcheck["sum_components"] - fcheck["total_funding_usd"]).abs() / fcheck["total_funding_usd"]
    out.write(f"- rows where |domestic+external - total| > 1%: {int((fcheck['diff_pct'] > 0.01).sum())}\n")

    out.write("\n### laboratory_capacity.csv\n")
    lab = frames["laboratory_capacity.csv"]
    out.write(numeric_ranges(lab, ["total_public_labs", "labs_iso15189_accredited",
                                   "iso15189_accreditation_pct", "avg_turnaround_time_days",
                                   "diagnostic_tests_per_100k"]))
    bad_acc = lab[lab["labs_iso15189_accredited"] > lab["total_public_labs"]]
    out.write(f"- accredited labs > total labs: {len(bad_acc)}\n")

    out.write("\n### disease_surveillance.csv\n")
    dis = frames["disease_surveillance.csv"]
    out.write(f"- diseases tracked: {sorted(dis['disease'].unique())}\n")
    out.write(numeric_ranges(dis, ["cases_reported", "deaths_reported",
                                   "attack_rate_per_100k", "case_fatality_ratio_pct"]))
    bad_cfr = dis[dis["deaths_reported"] > dis["cases_reported"]]
    out.write(f"- deaths > cases: {len(bad_cfr)}\n")

    out.write("\n### outbreaks.csv\n")
    ob = frames["outbreaks.csv"]
    out.write(f"- diseases: {sorted(ob['disease'].unique())}\n")
    out.write(numeric_ranges(ob, ["duration_days", "time_to_detection_days", "cases", "deaths"]))
    out.write(f"- distinct outbreak_id: {ob['outbreak_id'].nunique()} of {len(ob)} rows\n")
    out.write(f"- year range: {ob['year'].min()}-{ob['year'].max()}\n")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(out.getvalue())
    print(out.getvalue())
    print(f"\n\nReport written to {REPORT}")


if __name__ == "__main__":
    main()
